credentials:
  usernames:
    admin:
      email: "admin@example.com"
      name: "Administrador"
      password: "1234"   # senha simples sรณ para testes

cookie:
  expiry_days: 1
  key: "f1fantasy2025"
  name: "f1fantasy_cookie"

preauthorized:
  emails:
    - "admin@example.com"
